image: julia:1.8        # image comes from Docker hub

before_script:
    # - export
    #- echo $(pwd)
    #- echo $(ls ./)
    ## - julia --project=@. -e 'ENV["JULIA_PKG_USE_CLI_GIT"]=true; using Pkg; Pkg.add(url="https://gitlab.com/JuliaGeoph/GeoPolygons.jl")'
    ## The General registry MUST be added explicitly otherwise only JuliaGeophRegistry will be available.
    - julia --project=@. -e 'import Pkg; Pkg.Registry.add("General"); Pkg.Registry.add( Pkg.RegistrySpec(url="https://gitlab.com/JuliaGeoph/JuliaGeophRegistry"))'
    - julia --project=@. -e 'import Pkg; Pkg.Registry.status()'
    - julia --project=@. -e 'import Pkg; Pkg.build()'
    - apt-get -qq update; apt-get -y install git rsync

default:
  stage: test
  script:
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage = false)"
    # - julia --project=test/coverage -e 'import Pkg; Pkg.instantiate()'
    # - julia --project=test/coverage test/coverage/coverage-summary.jl


# pages:
#   stage: deploy
#   script:
#     - julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
#     - julia --project=docs --color=yes docs/make.jl
#     #- echo $(ls ./)
#     # - git branch -a
#     ## the following lines needed to have versioned docs from Documenter.jl
#     - mkdir tmppub ; mv .git tmppub/
#     - cd tmppub
#     - echo $(ls -a) 
#     - git fetch; git checkout gl-pages ; git pull 
#     - echo $(ls )
#     - rsync -a --exclude=".git" --exclude=".gitignore" ../tmppub/*  ../public/
#     # - echo $(ls  docs/build/)
#     ## - mv docs/build public # move to the directory picked up by Gitlab pages
#   artifacts:
#     paths:
#       - public
#   rules:
#     - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG ) && $DOCUMENTER_KEY    
#     #- if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG ) && $DOCUMENTER_KEY 
