zeros(x) = @zeros(x)
ones(x) = @ones(x)
zeros(x, y) = @zeros(x, y)
ones(x, y) = @ones(x, y)
zeros(x, y, z) = @zeros(x, y, z)
ones(x, y, z) = @ones(x, y, z)
zeros(x, y, z, t) = @zeros(x, y, z, t)
ones(x, y, z, t) = @ones(x, y, z, t)
